/*
 * Copyright (c) 2022-2026, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.nvidia.spark.rapids

import org.apache.spark.sql.connector.read.Scan
import org.apache.spark.sql.execution.metric.SQLMetrics

trait GpuBatchScanExecMetrics extends GpuExec {
  import GpuMetric._

  def scan: Scan

  override def supportsColumnar = true

  override val outputRowsLevel: MetricsLevel = ESSENTIAL_LEVEL
  override val outputBatchesLevel: MetricsLevel = MODERATE_LEVEL
  override lazy val additionalMetrics: Map[String, GpuMetric] = Map(
    GPU_DECODE_TIME -> createNanoTimingMetric(MODERATE_LEVEL, DESCRIPTION_GPU_DECODE_TIME),
    BUFFER_TIME -> createNanoTimingMetric(MODERATE_LEVEL, DESCRIPTION_BUFFER_TIME),
    FILTER_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_FILTER_TIME),
    SCHEDULE_TIME -> createNanoTimingMetric(MODERATE_LEVEL, DESCRIPTION_SCHEDULE_TIME),
    ASYNC_RAW_QUEUE_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_QUEUE_TIME),
    ASYNC_RAW_EXECUTION_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_EXECUTION_TIME),
    ASYNC_RAW_FILTER_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_FILTER_TIME),
    ASYNC_RAW_BUFFER_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_BUFFER_TIME),
    ORC_FILTER_CPU_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_FILTER_CPU_TIME),
    ORC_BUFFER_CPU_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_BUFFER_CPU_TIME),
    ORC_FS_LOOKUP_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_FS_LOOKUP_TIME),
    ORC_TAIL_CACHE_LOOKUP_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_TAIL_CACHE_LOOKUP_TIME),
    ORC_TAIL_READ_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_TAIL_READ_TIME),
    ORC_TAIL_READ_BYTES -> createSizeMetric(DEBUG_LEVEL, DESCRIPTION_ORC_TAIL_READ_BYTES),
    ORC_TAIL_READ_CALLS -> createMetric(DEBUG_LEVEL, DESCRIPTION_ORC_TAIL_READ_CALLS),
    ORC_TAIL_PERFIO_READ_CALLS ->
      createMetric(DEBUG_LEVEL, DESCRIPTION_ORC_TAIL_PERFIO_READ_CALLS),
    ORC_TAIL_FALLBACK_READ_CALLS ->
      createMetric(DEBUG_LEVEL, DESCRIPTION_ORC_TAIL_FALLBACK_READ_CALLS),
    ORC_TAIL_PARSE_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_TAIL_PARSE_TIME),
    ORC_READER_FILTER_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_READER_FILTER_TIME),
    ORC_STRIPE_FOOTER_READ_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_STRIPE_FOOTER_READ_TIME),
    ORC_STRIPE_FOOTER_READ_BYTES ->
      createSizeMetric(DEBUG_LEVEL, DESCRIPTION_ORC_STRIPE_FOOTER_READ_BYTES),
    ORC_STRIPE_FOOTER_READ_CALLS ->
      createMetric(DEBUG_LEVEL, DESCRIPTION_ORC_STRIPE_FOOTER_READ_CALLS),
    ORC_STRIPE_FOOTER_PARSE_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_STRIPE_FOOTER_PARSE_TIME),
    ORC_OUTPUT_SIZE_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_OUTPUT_SIZE_TIME),
    ORC_HOST_BUFFER_ALLOC_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_HOST_BUFFER_ALLOC_TIME),
    ORC_REMOTE_OPEN_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_REMOTE_OPEN_TIME),
    ORC_REMOTE_READ_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_REMOTE_READ_TIME),
    ORC_REMOTE_READ_BYTES -> createSizeMetric(DEBUG_LEVEL, DESCRIPTION_ORC_REMOTE_READ_BYTES),
    ORC_REMOTE_READ_CALLS -> createMetric(DEBUG_LEVEL, DESCRIPTION_ORC_REMOTE_READ_CALLS),
    ORC_HOST_COPY_TIME -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_HOST_COPY_TIME),
    ORC_FILE_REBUILD_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_FILE_REBUILD_TIME),
    ORC_SPILLABLE_WRAP_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ORC_SPILLABLE_WRAP_TIME),
    ASYNC_RAW_PARQUET_CHUNK_SELECTION_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_CHUNK_SELECTION_TIME),
    ASYNC_RAW_PARQUET_PART_FILE_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_PART_FILE_TIME),
    ASYNC_RAW_PARQUET_PART_BOOKKEEPING_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_PART_BOOKKEEPING_TIME),
    ASYNC_RAW_PARQUET_RESULT_ASSEMBLY_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_RESULT_ASSEMBLY_TIME),
    ASYNC_RAW_PARQUET_BUFFER_RESIDUAL_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_BUFFER_RESIDUAL_TIME),
    ASYNC_RAW_PARQUET_OUTPUT_SIZE_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_OUTPUT_SIZE_TIME),
    ASYNC_RAW_PARQUET_HOST_BUFFER_ALLOC_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_HOST_BUFFER_ALLOC_TIME),
    ASYNC_RAW_PARQUET_BLOCK_COPY_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_BLOCK_COPY_TIME),
    ASYNC_RAW_PARQUET_FOOTER_WRITE_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_FOOTER_WRITE_TIME),
    ASYNC_RAW_PARQUET_SPILLABLE_WRAP_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_SPILLABLE_WRAP_TIME),
    ASYNC_RAW_PARQUET_PART_FILE_RESIDUAL_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_PART_FILE_RESIDUAL_TIME),
    ASYNC_RAW_PARQUET_RANGE_PREP_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_RANGE_PREP_TIME),
    ASYNC_RAW_PARQUET_LOCAL_COPY_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_LOCAL_COPY_TIME),
    ASYNC_RAW_PARQUET_VECTORED_READ_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_VECTORED_READ_TIME),
    ASYNC_RAW_PARQUET_REMOTE_CACHE_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_REMOTE_CACHE_TIME),
    ASYNC_RAW_PARQUET_BLOCK_METADATA_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_BLOCK_METADATA_TIME),
    ASYNC_RAW_PARQUET_BLOCK_COPY_RESIDUAL_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_RAW_PARQUET_BLOCK_COPY_RESIDUAL_TIME),
    ASYNC_FUTURE_WAIT_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_FUTURE_WAIT_TIME),
    ASYNC_FUTURE_WAIT_QUEUE_OVERLAP_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_FUTURE_WAIT_QUEUE_OVERLAP_TIME),
    ASYNC_FUTURE_WAIT_EXECUTION_OVERLAP_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_FUTURE_WAIT_EXECUTION_OVERLAP_TIME),
    ASYNC_FUTURE_WAIT_RESIDUAL_TIME ->
      createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_ASYNC_FUTURE_WAIT_RESIDUAL_TIME),
    BUFFER_TIME_BUBBLE -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_BUFFER_TIME_BUBBLE),
    FILTER_TIME_BUBBLE -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_FILTER_TIME_BUBBLE),
    SCHEDULE_TIME_BUBBLE -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_SCHEDULE_TIME_BUBBLE),
    OP_TIME_LEGACY -> createNanoTimingMetric(DEBUG_LEVEL, DESCRIPTION_OP_TIME_LEGACY),
    JOIN_TIME -> createNanoTimingMetric(MODERATE_LEVEL, DESCRIPTION_JOIN_TIME),
    ICEBERG_BUILD_ACTION_TIME ->
      createNanoTimingMetric(MODERATE_LEVEL, DESCRIPTION_ICEBERG_BUILD_ACTION_TIME),
    ICEBERG_POST_PROCESS_TIME ->
      createNanoTimingMetric(MODERATE_LEVEL, DESCRIPTION_ICEBERG_POST_PROCESS_TIME),
  ) ++ fileCacheMetrics ++ scanCustomMetrics

  lazy val fileCacheMetrics: Map[String, GpuMetric] = createFileCacheMetrics()

  private lazy val scanCustomMetrics: Map[String, GpuMetric] = {
    scan.supportedCustomMetrics().map { metric =>
      metric.name() -> WrappedGpuMetric(SQLMetrics.createV2CustomMetric(sparkContext, metric))
    }.toMap
  }
}
